apple: "http://s3.amazonaws.com/MinecraftSkins/MHF_Apple.png"
arrowdown: "http://s3.amazonaws.com/MinecraftSkins/MHF_ArrowDown.png"
arrowleft: "http://s3.amazonaws.com/MinecraftSkins/MHF_ArrowLeft.png"
arrowright: "http://s3.amazonaws.com/MinecraftSkins/MHF_ArrowRight.png"
arrowup: "http://s3.amazonaws.com/MinecraftSkins/MHF_ArrowUp.png"
blaze: "http://s3.amazonaws.com/MinecraftSkins/MHF_Blaze.png"
cactus: "http://s3.amazonaws.com/MinecraftSkins/MHF_Cactus.png"
cake: "http://s3.amazonaws.com/MinecraftSkins/MHF_Cake.png"
cavespider: "http://s3.amazonaws.com/MinecraftSkins/MHF_CaveSpider.png"
chest: "http://s3.amazonaws.com/MinecraftSkins/MHF_Chest.png"
chicken: "http://s3.amazonaws.com/MinecraftSkins/MHF_Chicken.png"
cow: "http://s3.amazonaws.com/MinecraftSkins/MHF_Cow.png"
enderman: "http://s3.amazonaws.com/MinecraftSkins/MHF_Enderman.png"
exclamation: "http://s3.amazonaws.com/MinecraftSkins/MHF_Exclamation.png"
golem: "http://s3.amazonaws.com/MinecraftSkins/MHF_Golem.png"
herobrine: "http://s3.amazonaws.com/MinecraftSkins/MHF_Herobrine.png"
jukebox: "http://s3.amazonaws.com/MinecraftSkins/C418.png"
lavaslime: "http://s3.amazonaws.com/MinecraftSkins/MHF_LavaSlime.png"
melon: "http://s3.amazonaws.com/MinecraftSkins/MHF_Melon.png"
mushroomcow: "http://s3.amazonaws.com/MinecraftSkins/MHF_MushroomCow.png"
oaklog: "http://s3.amazonaws.com/MinecraftSkins/MHF_OakLog.png"
ocelot: "http://s3.amazonaws.com/MinecraftSkins/MHF_Ocelot.png"
pigzombie: "http://s3.amazonaws.com/MinecraftSkins/MHF_PigZombie.png"
pig: "http://s3.amazonaws.com/MinecraftSkins/MHF_Pig.png"
pumpkin: "http://s3.amazonaws.com/MinecraftSkins/MHF_Pumpkin.png"
question: "http://s3.amazonaws.com/MinecraftSkins/MHF_Question.png"
sheep: "http://s3.amazonaws.com/MinecraftSkins/MHF_Sheep.png"
slime: "http://s3.amazonaws.com/MinecraftSkins/MHF_Slime.png"
spider: "http://s3.amazonaws.com/MinecraftSkins/MHF_Spider.png"
squid: "http://s3.amazonaws.com/MinecraftSkins/MHF_Squid.png"
tnt2: "http://s3.amazonaws.com/MinecraftSkins/MHF_TNT2.png"
tnt: "http://s3.amazonaws.com/MinecraftSkins/MHF_TNT.png"
villager: "http://s3.amazonaws.com/MinecraftSkins/MHF_Villager.png"
ghast: "http://s3.amazonaws.com/MinecraftSkins/MHF_Ghast.png"